import json
from langchain_core.messages import HumanMessage, ToolMessage
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

load_dotenv()

# 1. Define tool
@tool
def query_database(table: str, limit: int = 5) -> str:
    """Query an internal SQL database by specifying table name and row limit."""
    # Mock data lookup
    sample_records = [
        {"id": 101, "status": "Shipped", "priority": "High"},
        {"id": 102, "status": "Pending", "priority": "Low"},
    ]
    return json.dumps(sample_records[:limit])

tools = [query_database]
tools_by_name = {tool.name: tool for tool in tools}

# 2. Bind the tools directly to the model
llm = ChatOpenAI(model="gpt-4o", temperature=0)
llm_with_tools = llm.bind_tools(tools)

# 3. Run initial query
messages = [HumanMessage(content="Pull the first 2 rows from the customer_orders table.")]
ai_message = llm_with_tools.invoke(messages)
messages.append(ai_message)

# 4. Inspect tool call payloads generated by the model
if ai_message.tool_calls:
    for tool_call in ai_message.tool_calls:
        tool_name = tool_call["name"]
        tool_args = tool_call["args"]
        call_id = tool_call["id"]

        print(f"Executing: {tool_name} with arguments: {tool_args}")

        # Execute the function locally
        selected_tool = tools_by_name[tool_name]
        tool_output = selected_tool.invoke(tool_args)

        # 5. Inject observation back into message chain with corresponding tool_call_id
        messages.append(ToolMessage(content=str(tool_output), tool_call_id=call_id))

    # 6. Final synthesis turn with observations in context
    final_response = llm_with_tools.invoke(messages)
    print("\nFinal Answer:\n", final_response.content)