[project]
name = "aiagentworkspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"langchain",
	"langchain-core",
	"langchain-mcp-adapters>=0.3.2",
	"langchain-openai",
	"langgraph",
	"langgraph-checkpoint-sqlite",
	"mcp>=1.30.0",
	"python-dotenv",
]
